Update mainnet signers
sygmaprotocol/community-executions pull request #4
Opened 2023-07-07 17:19 UTC by ansermino

Adds Wenfeng (0x0c1db86328E6CFCD4f530401131Dc9a26DefA12a)

2023-07-12 16:17 UTC, MakMuftic approved these changes

2023-07-12 16:18 UTC, MakMuftic requested changes
@ansermino did we also change threshold to be 4? As we need to update this info inside README also.

2023-07-13 06:53 UTC, MakMuftic approved these changes

2023-11-13 10:00 UTC, nmlinaric approved these changes

2023-11-13 10:01 UTC, merged